import assert from "node:assert/strict";
import { test } from "node:test";
import { dependabotUpdates, renderDependabotYaml } from "../scripts/dependabot-policy.mjs";

test("renders deterministic root npm and github-actions updates", () => {
  const yaml = renderDependabotYaml({
    dependabot: {
      managed: true,
      github_actions: true,
      npm: true,
      uv: false,
      pip: false,
      bundler: false,
    },
  });
  assert.match(yaml, /package-ecosystem: "github-actions"/);
  assert.match(yaml, /package-ecosystem: "npm"/);
  assert.match(yaml, /Source and mirror repositories keep this file identical/);
});

test("renders uv and pip directory from policy without deleting source parity file", () => {
  const updates = dependabotUpdates({
    dependabot: {
      managed: true,
      keep_source_file_for_parity: true,
      source_settings_disabled: true,
      github_actions: true,
      uv: true,
      uv_directory: "/fovux-mcp",
      pip: true,
      pip_directory: "/fovux-mcp",
    },
  });
  assert.deepEqual(
    updates.map((update) => [update.package_ecosystem, update.directory]),
    [
      ["github-actions", "/"],
      ["uv", "/fovux-mcp"],
      ["pip", "/fovux-mcp"],
    ],
  );
});

test("managed=false renders an inert empty updates list", () => {
  assert.equal(renderDependabotYaml({ dependabot: { managed: false, github_actions: true } }), "version: 2\nupdates:\n  []\n".replace("version", "# Generated by oaslananka-lab/_ops. Do not edit manually.\n# Source and mirror repositories keep this file identical; repository settings decide whether it is active.\nversion"));
});
