#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { resolvePolicy } from "./ops-policy.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const ECOSYSTEMS = [
  ["github_actions", "github-actions", "weekly", 5],
  ["npm", "npm", "daily", 10],
  ["uv", "uv", "daily", 10],
  ["pip", "pip", "daily", 10],
  ["bundler", "bundler", "weekly", 5],
];

function scalar(value, fallback) {
  if (value === undefined || value === null || value === "") return fallback;
  return String(value);
}

function integer(value, fallback) {
  return Number.isInteger(value) ? value : fallback;
}

export function dependabotUpdates(policy) {
  const dependabot = policy.dependabot || {};
  if (dependabot.managed === false) return [];
  const updates = [];
  for (const [key, ecosystem, defaultInterval, defaultLimit] of ECOSYSTEMS) {
    if (dependabot[key] !== true) continue;
    updates.push({
      package_ecosystem: ecosystem,
      directory: scalar(dependabot[`${key}_directory`], "/"),
      schedule_interval: scalar(dependabot[`${key}_schedule_interval`], defaultInterval),
      open_pull_requests_limit: integer(dependabot[`${key}_open_pull_requests_limit`], defaultLimit),
      labels: labelsFor(ecosystem),
    });
  }
  return updates;
}

function labelsFor(ecosystem) {
  if (ecosystem === "github-actions") return ["dependencies", "github-actions"];
  return ["dependencies", ecosystem];
}

function quote(value) {
  return JSON.stringify(value);
}

export function renderDependabotYaml(policy) {
  const updates = dependabotUpdates(policy);
  const lines = [
    "# Generated by oaslananka-lab/_ops. Do not edit manually.",
    "# Source and mirror repositories keep this file identical; repository settings decide whether it is active.",
    "version: 2",
    "updates:",
  ];
  if (updates.length === 0) {
    lines.push("  []");
    return `${lines.join("\n")}\n`;
  }
  for (const update of updates) {
    lines.push(`  - package-ecosystem: ${quote(update.package_ecosystem)}`);
    lines.push(`    directory: ${quote(update.directory)}`);
    lines.push("    schedule:");
    lines.push(`      interval: ${quote(update.schedule_interval)}`);
    lines.push(`    open-pull-requests-limit: ${update.open_pull_requests_limit}`);
    lines.push("    labels:");
    for (const label of update.labels) lines.push(`      - ${quote(label)}`);
  }
  return `${lines.join("\n")}\n`;
}

export function mirrorPolicyForRepo(repo) {
  return resolvePolicy("oaslananka-lab", repo);
}

export function managedMirrorRepos() {
  const dir = path.join(ROOT, "config", "repos", "oaslananka-lab");
  return fs
    .readdirSync(dir)
    .filter((file) => file.endsWith(".yml"))
    .map((file) => file.slice(0, -4))
    .filter((repo) => {
      const policy = mirrorPolicyForRepo(repo);
      return policy.mirror?.enabled === true && policy.dependabot?.managed !== false;
    })
    .sort();
}

function parseArgs(argv) {
  const args = { command: argv[0] || "render" };
  for (let index = 1; index < argv.length; index += 1) {
    const key = argv[index];
    if (!key.startsWith("--")) throw new Error(`Unexpected argument: ${key}`);
    args[key.slice(2).replace(/-([a-z])/g, (_, c) => c.toUpperCase())] = argv[index + 1];
    index += 1;
  }
  return args;
}

export function main(argv = process.argv.slice(2)) {
  const args = parseArgs(argv);
  if (args.command === "list") {
    process.stdout.write(`${JSON.stringify(managedMirrorRepos(), null, 2)}\n`);
    return;
  }
  if (!args.repo) throw new Error("--repo is required");
  const policy = mirrorPolicyForRepo(args.repo);
  if (args.command === "render") {
    process.stdout.write(renderDependabotYaml(policy));
    return;
  }
  if (args.command === "summary") {
    process.stdout.write(
      `${JSON.stringify(
        {
          repo: args.repo,
          source: `${policy.mirror.source_owner}/${policy.mirror.source_repo}`,
          mirror: `${policy.mirror.mirror_owner}/${policy.mirror.mirror_repo}`,
          managed: policy.dependabot?.managed !== false,
          updates: dependabotUpdates(policy),
        },
        null,
        2,
      )}\n`,
    );
    return;
  }
  throw new Error("Usage: dependabot-policy.mjs <render|summary|list> --repo REPO");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  try {
    main();
  } catch (error) {
    console.error(error.message);
    process.exit(1);
  }
}
